apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/gcp-dev-tools/duct-tape/go
    context: go
  - image: gcr.io/gcp-dev-tools/duct-tape/python
    context: python
  - image: gcr.io/gcp-dev-tools/duct-tape/netcore
    context: netcore
  - image: gcr.io/gcp-dev-tools/duct-tape/nodejs
    context: nodejs
test:
  - image: gcr.io/gcp-dev-tools/duct-tape/go
    structureTests: [./test/structure-tests-go.yaml]
  - image: gcr.io/gcp-dev-tools/duct-tape/python
    structureTests: [./test/structure-tests-python.yaml]
  - image: gcr.io/gcp-dev-tools/duct-tape/netcore
    structureTests: [./test/structure-tests-netcore.yaml]
  - image: gcr.io/gcp-dev-tools/duct-tape/nodejs
    structureTests: [./test/structure-tests-nodejs.yaml]

profiles:
  # local: builds to local daemon only
  - name: local
    build:
      local:
        push: false

  - name: test
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: go113
          context: test/goapp
          docker:
            buildArgs:
              GOVERSION: 1.13
      - op: add
        path: /build/artifacts/-
        value:
          image: go114
          context: test/goapp
          docker:
            buildArgs:
              GOVERSION: 1.14
    deploy:
      kubectl:
        manifests:
          - test/k8s-test-installation.yaml
          - test/k8s-go113-connect-job.yaml
          - test/k8s-go114-connect-job.yaml

  # prod: pushes images to production with :latest
  - name: prod
    build:
      local:
        push: true
      tagPolicy:
        envTemplate:
          template: '{{.IMAGE_NAME}}:latest'
